<?php

//Created by ESL!!!

declare(strict_types=1);

use Fisharebest\Webtrees\Date; #ESL!!!
use Fisharebest\Webtrees\Auth;
use Fisharebest\Webtrees\Fact;
use Fisharebest\Webtrees\Gedcom;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Menu;
use Fisharebest\Webtrees\Module\ModuleChartInterface;
use Fisharebest\Webtrees\Registry;
use Fisharebest\Webtrees\Services\ModuleService;
use Illuminate\Support\Collection;
use Mitalteli\Webtrees\Chart\EnhancedFamilyBookChart\EnhancedFamilyBookChartModule;

/**
 * @var Individual|null   $family
 * @var ModuleService     $module_service
 * @var Collection|Menu[] $menus
 * @var bool              $full_places
 */

if ($family === null) {
    echo '<div class="wt-chart-box"></div>';

    return;
}


foreach ($family->facts(['MARR']) as $marriage) {
    if ($marriage instanceof Fact) {
        if ($marriage->canShow()) {
            if ($family->tree()->getPreference('SHOW_HIGHLIGHT_IMAGES')) {

                $media = "";
                if (preg_match_all('/\n(2 OBJE\b.*(?:\n[^2].*)*)/', $marriage->gedcom(), $matches, PREG_SET_ORDER) > 0) {

                    $media = $matches[0][1];
                }

            }  # SHOW_HIGHLIGHT_IMAGES

            $module_service = EnhancedFamilyBookChartModule::getClass(ModuleService::class);
            
            // Do not show these facts in the expanded chart boxes.
            $exclude = [
                'FAM:CHAN',
                'FAM:CHIL',
                'FAM:HUSB',
                'FAM:NOTE',
                'FAM:OBJE',
                'FAM:RESN',
                'FAM:SOUR',
                'FAM:WIFE',
                'INDI:ADDR',
                'INDI:ALIA',
                'INDI:ASSO',
                'INDI:CHAN',
                'INDI:EMAIL',
                'INDI:FAMC',
                'INDI:FAMS',
                'INDI:NAME',
                'INDI:NOTE',
                'INDI:OBJE',
                'INDI:PHON',
                'INDI:RESI',
                'INDI:RESN',
                'INDI:SEX',
                'INDI:SOUR',
                'INDI:SSN',
                'INDI:SUBM',
                'INDI:TITL',
                'INDI:URL',
                'INDI:WWW',
                'INDI:_EMAIL',
                'INDI:_TODO',
                'INDI:_UID',
                'INDI:_WT_OBJE_SORT'
            ];
            
            /** @var Collection|Fact[] $all_facts */
            $all_facts = $family->facts();
            
            $id = Registry::idFactory()->id();

?>

            <div class="wt-chart-box wt-chart-box-fact <?= $family->isPendingAddition() ? 'wt-new' : '' ?> <?= $family->isPendingDeletion() ? 'wt-old' : '' ?> overflow-hidden" data-wt-chart-xref="<?= e($family->xref()) ?>" data-tree="<?= e($family->tree()->name()) ?>">
                <?php if ($family->canShow() && $family->tree()->getPreference('SHOW_HIGHLIGHT_IMAGES')) : ?>
                    <div class="wt-chart-box-thumbnail float-start me-1">
                        <?= view($module . '::chart-box-icon-only', ['gedcom' => $media, 'parent' => $marriage->tag(), 'tree' => $marriage->record()->tree()]) ?>
                    </div>
                <?php endif ?>
            
                <?php if ($family->canShow()) : ?>
                    <div class="wt-chart-box-extra d-print-none float-end ms-1">
                        <div class="dropdown position-static wt-chart-box-zoom">
                            <a class="wt-chart-box-icon" href="#" role="button" id="chart-box-zoom-<?= $id ?>" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <div ><?= view('icons/zoom-in') ?></div>
                                <div class="d-none"><?= view('icons/zoom-out') ?></div>
                                <span class="visually-hidden"><?= I18N::translate('Links') ?></span>
                            </a>
                            <div class="dropdown-menu dropdown-menu-end wt-chart-box-dropdown wt-chart-box-zoom-dropdown" style="position: inherit" aria-labelledby="#chart-box-zoom-<?= $id ?>">
                                <hr/>
                                <?php foreach ($all_facts as $fact) : ?>
                                    <?php if($full_places) : ?>
                                        <?php $summaryStr = $fact->summary(); ?>
                                        <?php $summaryPlace = $fact->place()->shortName(); ?>
                                        <?php $fullPlace = $fact->place()->fullName(); ?>
                                        <?= str_replace($summaryPlace, $fullPlace, $summaryStr) . "aaa" ?>
                                    <?php else : ?>
                                        <?= $fact->summary() . "bbb"?>
                                    <?php endif; ?>
                                <?php endforeach ?>
                            </div>
                        </div>
                    </div>
                <?php endif ?>
            
                <div class="wt-chart-box-facts">
                    <div class="wt-chart-box-fact small">
                    <?php $summaryStr = $marriage->summary(); ?>
                    <?php if($full_places) : ?>
                        <?php $summaryPlace = $marriage->place()->shortName(); ?>
                        <?php $fullPlace = $marriage->place()->fullName(); ?>
                        <?php $summaryStr = str_replace($summaryPlace, $fullPlace, $summaryStr) ?>
                    <?php endif; ?>
                    <?php if ($family->canShow()) : ?>
                        <a href="<?= e($family->url()) ?>"><?= $summaryStr ?></a>
                    <?php else : ?>
                        <?= $summaryStr . "ccc" ?>
                    <?php endif ?>
                    </div>
                </div>
                <div class="wt-chart-box-name">
                    <?php if ($family->canShow()) : ?>
                        <a href="<?= e($family->url()) ?>"><?= $family->fullName() ?></a>
                    <?php else : ?>
                        <?= $family->fullName() ?>
                    <?php endif ?>
                </div>
            
                <div class="wt-chart-box-name wt-chart-box-name-alt">
                    <?= $family->alternateName() ?>
                </div>
            
                <div class="wt-chart-box-facts">
                    <div class="wt-chart-box-fact small">
                        <?php $opt_tags = preg_split('/\W/', $family->tree()->getPreference('CHART_BOX_TAGS'), 0, PREG_SPLIT_NO_EMPTY); ?>
                    </div>
                </div>
            </div>
<?php

        } # canShow
    } # instanceof Fact
} # foreach
?>
