<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Family;
use Fisharebest\Webtrees\Individual;
use Illuminate\Support\Collection;

/**
 * @var Collection<int,Individual> $children
 * @var int                        $generations
 * @var int                        $places_format
 * @var bool                       $extra_images
 */

?>
<div class="align-self-center">
    <?php foreach ($children as $n => $child) : ?>
        <?php $grandchildren = $child->spouseFamilies()->map(static function (Family $family): Collection {
    return $family->children();
        })->flatten() ?>
        <div class="d-flex justify-content-end">
            <?php if ($generations > 1 && $grandchildren->isNotEmpty()) : ?>
                <?= view($module_name . '::modules/mitalteli-family-book-chart/children', ['children' => $grandchildren, 'generations' => $generations - 1, 'places_format' => $places_format, 'extra_images' => $extra_images, 'module_name' => $module_name, 'module' => $module]) ?>
            <?php endif ?>
            <div class="align-self-center">
                <?= view($module_name . '::chart-box', ['individual' => $child, 'places_format' => $places_format, 'extra_images' => $extra_images, 'module_name' => $module_name, 'module' => $module]) ?>
            </div>
            <div class="wt-chart-horizontal-spacer">
                <?php if ($children->count() === 1) : ?>
                    <div class="wt-chart-horizontal-line"></div>
                <?php elseif ($n === 0) : ?>
                    <div class="wt-chart-horizontal-first-child"></div>
                <?php elseif ($n + 1 === $children->count()) : ?>
                    <div class="wt-chart-horizontal-last-child"></div>
                <?php else : ?>
                    <div class="wt-chart-horizontal-middle-child">
                        <div class="wt-chart-horizontal-line"></div>
                    </div>
                <?php endif ?>
            </div>
        </div>
    <?php endforeach ?>
</div>
<?php if ($children->count() > 0) : ?>
    <div class="wt-chart-horizontal-spacer">
        <div class="wt-chart-horizontal-line"></div>
    </div>
<?php endif ?>
