<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Family;

/**
 * @var Family|null $family
 * @var int         $generations
 * @var bool        $spouses
 * @var bool        $marriages
 * @var bool        $divorces
 * @var int         $places_format
 * @var bool        $extra_images
 * @var String      $module_name
 * @var Object      $module
 */

?>
<div class="d-flex">
    <div class="align-self-center">
        <div class="d-flex">
            <div class="wt-chart-horizontal-spacer">
                <div class="wt-chart-horizontal-first-parent"></div>
            </div>

            <div class="align-self-center">
                <?= view($module_name . '::chart-box', ['individual' => $family ? $family->husband() : null, 'places_format' => $places_format, 'extra_images' => $extra_images, 'module_name' => $module_name, 'module' => $module, 'debug' => $debug]) ?>
            </div>

            <?php if ($generations > 1) : ?>
                <div class="wt-chart-horizontal-spacer">
                    <div class="wt-chart-horizontal-line"></div>
                </div>

                <?= view($module_name . '::modules/mitalteli-family-book-chart/parents', ['family' => $family && $family->husband() ? $family->husband()->childFamilies()->first() : null, 'generations' => $generations - 1, 'spouses' => $spouses, 'marriages' => $marriages, 'divorces' => $divorces, 'places_format' => $places_format, 'extra_images' => $extra_images, 'module_name' => $module_name, 'module' => $module, 'debug' => $debug]) ?>
            <?php endif ?>
        </div>

        <?php if ($spouses and $marriages and $family !== null and $family->facts(['MARR']) !== null and !$family->facts(['MARR'])->isEmpty()) : ?>

            <style type="text/css">
                .wt-chart-vertical-parent-marriage{height:100%;border-left:thin solid gray;border-left:var(--chart-line)}
                .wt-chart-horizontal-parent-marriage{height:50%;border-bottom: var(--chart-line)}
            </style>
    
            <div class="d-flex">
                <div class="wt-chart-horizontal-spacer">
                    <div class="wt-chart-vertical-parent-marriage">
                        <div class="wt-chart-horizontal-parent-marriage"></div>
                    </div>
                </div>
                            <div class="align-self-center"><?= view($module_name . '::chart-box-marriage', ['family' => $family, 'places_format' => $places_format, 'module_name' => $module_name, 'module' => $module, 'debug' => $debug]) ?></div>
            </div>

        <?php endif ?>

        <?php if ($spouses and $divorces and $family !== null and $family->facts(['DIV']) !== null and !$family->facts(['DIV'])->isEmpty()) : ?>

            <style type="text/css">
                .wt-chart-vertical-parent-divorce{height:100%;border-left:thin solid gray;border-left:var(--chart-line)}
                .wt-chart-horizontal-parent-divorce{height:50%;border-bottom: var(--chart-line)}
            </style>
    
            <div class="d-flex">
                <div class="wt-chart-horizontal-spacer">
                    <div class="wt-chart-vertical-parent-divorce">
                        <div class="wt-chart-horizontal-parent-divorce"></div>
                    </div>
                </div>
                    <?php
                    #$module::debugMessage(/*$pPrefix*/ "PPP1", /*$pMsgLog*/ '', /*$pMsgStd*/ '', /*$pSuffix*/ '', /*$pToLog*/ true, /*$pToStd*/ true, /*$pWithTime*/ true);
                    ?>
                            <div class="align-self-center"><?= view($module_name . '::chart-box-divorce', ['family' => $family, 'places_format' => $places_format, 'module_name' => $module_name, 'module' => $module, 'debug' => $debug]) ?></div>
            </div>

        <?php endif ?>

        <div class="d-flex">
            <div class="wt-chart-horizontal-spacer">
                <div class="wt-chart-horizontal-last-parent"></div>
            </div>

            <div class="align-self-center">
                <?= view($module_name . '::chart-box', ['individual' => $family ? $family->wife() : null, 'places_format' => $places_format, 'extra_images' => $extra_images, 'module_name' => $module_name, 'module' => $module, 'debug' => $debug]) ?>
            </div>

            <?php if ($generations > 1) : ?>
                <div class="wt-chart-horizontal-spacer">
                    <div class="wt-chart-horizontal-line"></div>
                </div>

                <?= view($module_name . '::modules/mitalteli-family-book-chart/parents', ['family' => $family && $family->wife() ? $family->wife()->childFamilies()->first() : null, 'generations' => $generations - 1, 'spouses' => $spouses, 'marriages' => $marriages, 'divorces' => $divorces, 'places_format' => $places_format, 'extra_images' => $extra_images, 'module_name' => $module_name, 'module' => $module, 'debug' => $debug]) ?>
            <?php endif ?>
        </div>
    </div>
</div>

